a = int(input('Nhap so dau tien: '))
b = int(input('Nhap so thu hai: '))
print(int(a+b))
print(float(a+b))
print(int(a-b))
print(float(a-b))
print(int(a*b))
print(float(a*b))
print(int(a/b))
print(float(a/b))
